### ISSUE TITLE
Installation guide "moved"

### ISSUE THREAD

**Issue by OKNoah** [pelias/documentation#225]
Click this link and follow the links to where the install guide has moved: https://github.com/pelias/documentation/blob/master/installing.md

It takes you in circles, with each page telling you the guide has "moved" to the other. In fact neither page has the guide.

**Comment by orangejulius** [comment]
Oops, thanks for catching this. I knew something like this would happen.

**Comment by orangejulius** [comment]
It should now be fixed in https://github.com/pelias/documentation/commit/073778897416bd28e99c8c21a5af904548ea0211 and https://github.com/pelias/pelias/commit/a7fb6ded1c9412f09ab98865e7ef4d4945b80dd0

We just did a major revamp of the documentation in #223, so thanks again for catching this.

**Comment by orangejulius** [comment]
This should be fixed. Let me know if you find any more broken links.
