### ISSUE TITLE
pelias from scratch shell script is crashing

### ISSUE THREAD

**Issue by GuidoS** [pelias/documentation#232]
# documentation/pelias_from_scratch.md

## Error

Using the shell script information [provided here](https://github.com/pelias/documentation/blob/master/pelias_from_scratch.md#download-the-pelias-repositories) I got the following error:

```
setup.sh: line 4: syntax error near unexpected token `interpolation'
setup.sh: line 4: `interpolation pip-service; do'
```

### setup.sh

```
#!/bin/bash

for repository in schema whosonfirst geonames openaddresses openstreetmap polylines api placeholder
interpolation pip-service; do
        git clone https://github.com/pelias/${repository}.git # clone from Github
        pushd $repository > /dev/null                         # switch into importer directory
        npm install                                           # install npm dependencies
        popd > /dev/null                                      # return to code directory
done
```

## Context

I am trying to work my way through pelias from scratch documentation using a vagrant machine. The instructions in the document feel vauge to me, I am not sure what I am supposed to do and there is no generic install shell script to help setup some basic process. I personally would like to setup a country wide geocoder.

I appreciate any help with this error and the larger process. I hope that this level of detail in my issue is helpful for others.

### Vargantfile

This is the Vargrantfile I am using which has embeded into it the requirements for the machine and a shell script for setting up the machine.

```sh
# -*- mode: ruby -*-
# vi: set ft=ruby :

## run in shell prior to running this vm
## vagrant plugin install vagrant-disksize

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # use ubuntu bionic
  config.vm.network "private_network", ip: "192.168.33.10"
  config.disksize.size = '50GB' # min requirement
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192" # min requirement
    vb.cpus = 2
  end

  # shell script to run first when vm is created (once)
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install build-essential libssl-dev
    curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    exec bash
    nvm install --lts
  SHELL
end
```

**Comment by orangejulius** [comment]
Hi @GuidoS,
Thanks for the report, it looks like an extra newline snuck into that bit of code, I've just fixed it in https://github.com/pelias/documentation/commit/226383029e7899cd6eae372183e2b74f2ce049d6.

As for the documentation in general, they're an attempt to strike a balance between covering everything and duplicating documentation for each of the Pelias components in their individual repositories.

Right now, we have the docker project for getting started, which is designed to hide as many details as possible, and then the from scratch guide is designed to proved much more. I've been thinking about something in the middle, like instructions on how to do a specific build of a medium sized area. aybe not the USA, as it would require several hundred GB of disk space, but a smaller country like Canada could work well.

I'd be interested to hear what thoughts you have or what areas in particular could be improved.
