### ISSUE TITLE
Confusion on what to use for full planet setup

### ISSUE THREAD

**Issue by androidseb** [pelias/documentation#238]
Hey, first of all, thank you for building this amazing tool with all the documentation, it looks very promising.

I would like to make a full planet setup on a single machine, but I was confused on what process to follow...

My first step was to look at this page:
https://github.com/pelias/documentation/blob/master/pelias_from_scratch.md
Where I found this:
```
We strongly recommend using our Docker tools for your first Pelias installation.
```

The link on the "Docker" word took me to that page:
https://github.com/pelias/docker/
One of the sections of that page says
```
Not suitable for large geographies
We do not recommend running large extracts (anything larger than a US State) inside Docker, the scripts are not suitable for full planet builds. If you require global coverage, please see our install documentation or consider using the geocode.earth services hosted by members of our core team.
```

The link on "install documentation" took me to that page:
https://github.com/pelias/documentation/blob/master/getting_started_install.md
Which had a link about "full planet build guide":
https://github.com/pelias/documentation/blob/master/full_planet_considerations.md
Then on that page, I found this:
```
Recommended processes
Use Docker containers and orchestration

We strongly recommend using Docker to run Pelias...
```

That made me wonder if I should use Docker for a full planet setup or not...

At this point, my assumption is that creating a full planet setup requires some knowledge with dividing up the work into multiple smaller Docker instances with an orchestrator, which is not something I could find in the documentation.

Maybe there is something obvious I missed here, but is there a step by step guide on how to setup pelias for the full planet on a single machine?

Thank you in advance for your help!

**Comment by jeremy-rutman** [comment]
I am in the same situation, its unclear whether using docker is recommended for full-planet or not

**Comment by orangejulius** [comment]
Hi @androidseb,
You weren't missing anything, our documentation has grown out of date as we've improved [pelias/docker](https://github.com/pelias/docker). It's now recommended for full planet builds as well (we've been using it for full planet builds for about 3 months now).

I've opened https://github.com/pelias/docker/pull/78  and https://github.com/pelias/documentation/pull/243 to reflect the new situation, let me know if that clears things up.

By the way, as mentioned in the getting started guide, we really recommend you do a small build before jumping into a full planet build. The full planet build does have the highest requirements in disk space, CPU, and time. It's easier to get a feel for Pelias with a smaller build.

If you've done one already, great, but I just wanted to make sure that was clear.

**Comment by androidseb** [comment]
Thank you for getting back to me.
I hadn't started anything yet, I need to familiarize myself with Docker and I wasn't sure if it was worth investing my time in Docker learning. Now that it's clear, I'll get to it.
Thank you for your help!
