### ISSUE TITLE
Total global coverage stats

### ISSUE THREAD

**Issue by mohammedayub44** [pelias/documentation#256]
Hi,

Just wondering if there are aggregated stats around which Continents / Countries are covered more  than others by Pelias in terms of percentage or numbers .  Or is it better to check the individual data sources if it has data from specific continent/ country. 
Any links or resources to the above would be helpful.

Thanks  !

**Comment by orangejulius** [comment]
There is some data which has now grown a bit out of date as part of the project's [coverage page](https://pelias.github.io/scripts-geocoding-coverage/index.html#).

This comes from the [coverage statistics repository](https://github.com/pelias/scripts-geocoding-coverage) which should still work, but realistically probably needs some maintenance after being left alone for a long time.

If it's something you're interested in we'd be happy to help you get started reviving it.

**Comment by mohammedayub44** [comment]
The coverage statistics repository was helpful. Thanks !
