### ISSUE TITLE
What domain to use for forward geocoding

### ISSUE THREAD

**Issue by mtarunsai1999** [pelias/documentation#257]
As the domain mapzen is not working, please let me know which domain to use or provide me a url pattern that I can use for forward geocoding

Thank you

Regards.

**Comment by orangejulius** [comment]
Mapzen [shut down](https://www.mapzen.com/blog/shutdown/) in January 2018.

Pelias itself does not offer hosted services, although you can run it yourself.

If you are looking for hosted geocoding you can sign up for a limited time free trial, or a permanent paid plan, at [geocode.earth](https://geocode.earth).

Feel free to open additional issues if you have questions about the Pelias project itself.
