### ISSUE TITLE
Is there any forums/slack group to discuss about addressing common isssues while setting up pelias ?

### ISSUE THREAD

**Issue by pravink** [pelias/documentation#260]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

Is there any forums/slack group to discuss about addressing common isssues while setting up pelias ? 
---
#### Here's what I did :innocent:

---
#### Here's what I got :scream_cat:

---
#### Here's what I was expecting :sparkles:

---

**Comment by orangejulius** [comment]
We use Gitter, and there's a decent number of people in https://gitter.im/pelias/pelias.
