### ISSUE TITLE
How to limit content and add custom attributs

### ISSUE THREAD

**Issue by haoujey** [pelias/documentation#261]
Hey team! 

I was using your awesome geocoding engine, and it's working great.

I have 2 very important questions, and i can't find a solution in the docs:
- How to limit the imported data to only restaurants ? Is it possible ? 

-In pelias there are less attributs than in osm, for example, restaurant opening hours. Is it possible to add these attributs ? is it possible for me to add my own attributs ? how ? 

Thank you for your help. 
Haoujey

**Comment by orangejulius** [comment]
Hi @haoujey,
You will likely want to take a look at the docs for the [OpenStreetMap importer](https://github.com/pelias/openstreetmap). It uses the [pbf2json](https://github.com/pelias/pbf2json) tool to bring in data from OSM.

pbf2json is quite configurable and you can probably use its [filtering tools](https://github.com/pelias/pbf2json#advanced-usage) to bring in only the records you want.

You can then also configure any additional fields to bring into the records. Take a look at https://github.com/pelias/openstreetmap/pull/494 as a model for how to do that.

Let us know if that helps.
