### ISSUE TITLE
distance unit is km not m

### ISSUE THREAD

**Issue by missinglink** [pelias/documentation#267]
A client pointed out that the `distance` property [seems to be in km](https://github.com/pelias/api/blob/master/middleware/distance.js#L31).

Our [reverse docs](https://github.com/pelias/documentation/blob/master/reverse.md#distance-and-confidence-scores-for-the-results) say "Each result returned has a distance from the query point (in meters)".

**Comment by orangejulius** [comment]
This was a good catch. I now wonder how consistent we are, both across our code and documentation, in using `km` vs meters. I would not be surprised to learn that at least some of the code uses meters as well.

**Comment by acondrat** [comment]
I noticed the same. Example take from https://github.com/pelias/documentation/blob/master/reverse.md#example-requests

https://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=51.5081124&point.lon=-0.0759493

```
"properties": {
        "id": "node/4200057922",
        "gid": "openstreetmap:venue:node/4200057922",
        "layer": "venue",
        "source": "openstreetmap",
        "source_id": "node/4200057922",
        "name": "White Tower",
        "confidence": 0.9,
        "distance": 0.009,
        "accuracy": "point",
...
      }
```
It can't be 0.009 meters.

**Comment by missinglink** [comment]
hi @acondrat, thanks for confirming, would you be interested in contributing a pull request which corrects the documentation?
https://github.com/pelias/documentation/blob/master/reverse.md#distance-and-confidence-scores-for-the-results

**Comment by acondrat** [comment]
https://github.com/pelias/documentation/pull/269

**Comment by missinglink** [comment]
resolved in https://github.com/pelias/documentation/pull/269
