### ISSUE TITLE
pelias main release?

### ISSUE THREAD

**Issue by stefanocudini** [pelias/documentation#276]
hi i was updating my production version with the latest updates to all modules, this works perfectly, but i would like to understand if there is a general versioning system for pelias.

I mean something that makes me understand at what stage of development it is globally.

I noticed that only the individual modules are versioned..
but docker version is not versioned.. https://github.com/pelias/docker

**Comment by orangejulius** [comment]
Hi @stefanocudini,

We don't have releases for Pelias as a whole, but I don't think we really made that clear anywhere. I've just opened https://github.com/pelias/documentation/pull/277 which _should_ clear that up. Let me know if you have further questions.

**Comment by stefanocudini** [comment]
today i updated my old pelias docker about 1 year ago .. and i couldn't explain to my colleagues what version i had brought the geocoder now.. :)
to get a general idea of the added improvements

it's more a matter of practice than technique

**Comment by stefanocudini** [comment]
I think about this that giving realease git tags to this repo could be a good idea to keep under control the versions of all modules
https://github.com/pelias/docker/tags

this seems useful to me to maintain compatibility between modules
